# Generated by Django 3.2.4 on 2021-06-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='link',
        ),
        migrations.AddField(
            model_name='profile',
            name='address_street',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cp',
            field=models.TextField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.TextField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.TextField(max_length=15, null=True),
        ),
    ]
